# Generated by Django 4.0.5 on 2022-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appartament',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='house',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
